# Change these first
owner: Riduidel # Your GitHub organization or username, where this repository lives
repo: aadarchi-upptime # The name of this repository

sites:
  - name: Aadarchi documentation
    url: https://riduidel.github.io/aadarchi/
    assignees:
      - Riduidel

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#  cname: demo.upptime.js.org
  baseUrl: /aadarchi-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for aadarchi just monitors the aadarchi important pages."
  introMessage: Aadarchi-upptime just monitors aadarchi documentation website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Aadarchi
      href: http://github.com/Riduidel/aadarchi
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
